# Site Settings
baseurl: ""
url: "https://marshmellowon.github.io/"
google_analytics: UA-164515885-1

# Blog Settings
theme_settings:
  title: marshmel.log
  description: marshmello's Blog
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/1582618759158.jpg
    username: Sangwon Lee
    description: Photograph & Programming
    experience:
      - start: 2020-08-01
        end:
        experience: TAVE, 6TH
      - start: 2020-03-02
        end:
        experience: INU, Information and Communication Engineering
    skills:
      - skill: PYTHON
        value: 10 # Percent value

  # Icons
  icons:
    email: leo503801@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: # Full URL
    github: Marshmellowon
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: s.wlli

  # Disqus
  disqus_shortname: "marshmellowon-github-io"

# Pagination
paginate: 7
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
