# Site Settings
baseurl: ""
url: "https://marshmellowon.github.io/"
google_analytics: G-D1WFVZ25Q7

# Blog Settings
theme_settings:
  title: marshmellog
  description: marshmello's Blog
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/profile.jpg
    username: Sangwon Lee
    description: Photograph & Programming
    experience:
      - start: 2020-12-20
        experience: TAVE Research
      - start: 2020-08-01
        end: 2020-11-28
        experience: TAVE, 6TH
        site_link: https://blog.naver.com/t-ave
        linkName: TAVE
      - start: 2020-03-02
        end:
        experience: INU [Information and Communication Engineering]
        site_link: http://www.inu.ac.kr/mbshome/mbs/inu/index.do
        linkName: INCHEON NATIONAL UNIVERSITY
    skills:
      - skill: PYTHON
        value: 10 # Percent value

  # Icons
  icons:
    email: marshmello.sw@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: # Full URL
    github: Marshmellowon
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: s.wlli

  # Disqus
  disqus_shortname: "marshmellowon-github-io"

# Pagination
paginate: 7
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
