title: Posts
description: My Personal Stack Problems
author: "[.log]"
github: https://github.com/Marshmellowon
about: Programming & Photo
disqus_shortname: "marshmellowon-github-io"
google_analytics: UA-164515885-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  - icon: fa-instagram
    link: "https://www.instagram.com/s.wlli/"
  - icon: fa-github
    link: "https://github.com/Marshmellowon"

share:
  twitter_username:
  fb_appid: 

urls:
  - text: About Me
    url: /about/
  - text: My Projects
    url: /projects/
  - text: XML Feed
    url: /feed.xml

url: "https://marshmellowon.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]
